import crypto from 'node:crypto';
// execSync is intentional here — the command strings are built by trusted
// buildSshExecCommand / buildScpCommand helpers (no user input), and they
// require shell interpretation for proper quoting. This mirrors the pattern
// already established in step-vm-setup.ts.
import { execSync } from 'node:child_process';
import { writeFileSync, unlinkSync } from 'node:fs';
import { writeFile, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import path from 'node:path';
import chalk from 'chalk';
import { shell } from '../utils/shell.js';
import { t } from '../i18n/index.js';
import { renderStepHeader } from '../ui/box.js';
import { withSpinner } from '../ui/spinner.js';
import {
  buildSshExecCommand,
  buildScpCommand,
  buildSshExecScriptCommand,
} from './step-vm-setup.js';
import type { InstallerContext, StepResult } from './types.js';

const TOTAL_STEPS = 12;
const VM_NAME = 'lox-vm';
const VPN_LISTEN_PORT = 51820;
const VPN_SERVER_IP = '10.10.0.1';
const VPN_CLIENT_IP = '10.10.0.3'; // Mac client (0.2 reserved for Arch)
const VPN_SUBNET = '10.10.0.0/24';
const HOST_INTERFACE = 'ens4'; // GCP default NIC

/**
 * Build the VM-side script that writes `/etc/wireguard/wg0.conf`, enables
 * IP forwarding, and (re)starts the wg-quick@wg0 service.
 *
 * Exported so tests can lock in the `restart` invariant (#99): on a step 8
 * re-run, `systemctl start` is a no-op when the service is already active,
 * so the WireGuard kernel interface keeps the previous peer keys loaded
 * even though the on-disk `wg0.conf` has new ones generated by the current
 * run. `restart` stops the service and re-reads the config, syncing kernel
 * state with the new keys every time step 8 runs.
 *
 * The script is intentionally newline-delimited (no `&&` chains) because
 * it's executed via cmd.exe on Windows, which mangles `&&` in single-arg
 * forms. See step-vm-setup.ts for the same pattern.
 */
export function buildServerDeployScript(serverConf: string): string {
  return [
    `echo '${serverConf}' | sudo tee /etc/wireguard/wg0.conf > /dev/null`,
    'sudo chmod 600 /etc/wireguard/wg0.conf',
    'sudo sysctl -w net.ipv4.ip_forward=1',
    'echo "net.ipv4.ip_forward=1" | sudo tee -a /etc/sysctl.conf > /dev/null',
    'sudo systemctl enable wg-quick@wg0',
    // NEVER change to `systemctl start` — see #99.
    'sudo systemctl restart wg-quick@wg0',
  ].join('\n');
}

/**
 * Execute a simple command on the VM via IAP tunnel SSH.
 * Uses execSync with buildSshExecCommand for Windows compatibility
 * (avoids cmd.exe interpreting && in shell() / execFile).
 */
function vpnSshExec(project: string, zone: string, command: string): string {
  const result = execSync(buildSshExecCommand(project, zone, command), {
    timeout: 30_000,
    stdio: 'pipe',
    encoding: 'utf-8',
  });
  return (result ?? '').trim();
}

/**
 * Execute a multi-line script on the VM via SCP + SSH.
 * Writes the script to a local temp file, SCPs it to the VM, then
 * executes it remotely. Avoids && chains that break on Windows cmd.exe.
 */
async function vpnSshExecScript(project: string, zone: string, script: string): Promise<string> {
  const suffix = crypto.randomBytes(4).toString('hex');
  const localTmp = join(tmpdir(), `lox-vpn-${suffix}.sh`);
  const remotePath = `/tmp/lox-vpn-${suffix}.sh`;
  writeFileSync(localTmp, script, { mode: 0o700 });
  try {
    execSync(buildScpCommand(project, zone, localTmp, remotePath), {
      timeout: 30_000,
      stdio: 'pipe',
    });
    const result = execSync(buildSshExecScriptCommand(project, zone, remotePath), {
      timeout: 30_000,
      stdio: 'pipe',
      encoding: 'utf-8',
    });
    return (result ?? '').trim();
  } finally {
    try { unlinkSync(localTmp); } catch { /* ignore */ }
  }
}

/**
 * Step 8: Allocate static IP, configure WireGuard server on VM,
 * generate client config locally, and activate the tunnel.
 */
export async function stepVpn(ctx: InstallerContext): Promise<StepResult> {
  const strings = t();
  const project = ctx.gcpProjectId;
  const zone = ctx.config.gcp?.zone;
  const region = ctx.config.gcp?.region;

  if (!project || !zone || !region) {
    return { success: false, message: 'GCP project, zone, or region not set. Run step 3 first.' };
  }

  console.log(renderStepHeader(8, TOTAL_STEPS, strings.step_wireguard));

  // Allocate static IP for VPN endpoint
  let staticIp: string;

  await withSpinner(
    `${strings.creating} static IP for VPN...`,
    async () => {
      try {
        await shell('gcloud', [
          'compute', 'addresses', 'create', 'lox-vpn-ip',
          '--region', region,
          '--project', project,
        ]);
      } catch {
        // Address may already exist
      }
    },
  );

  // Get the allocated IP
  const { stdout: ipOutput } = await shell('gcloud', [
    'compute', 'addresses', 'describe', 'lox-vpn-ip',
    '--region', region,
    '--format=value(address)',
    '--project', project,
  ]);
  staticIp = ipOutput.trim();

  if (!staticIp) {
    return { success: false, message: 'Failed to allocate static IP for VPN.' };
  }

  // Attach static IP to VM
  await withSpinner(
    `Attaching static IP ${staticIp} to VM...`,
    async () => {
      try {
        await shell('gcloud', [
          'compute', 'instances', 'add-access-config', VM_NAME,
          '--zone', zone,
          '--access-config-name=vpn-only',
          `--address=${staticIp}`,
          '--project', project,
        ]);
      } catch {
        // Access config may already exist; delete and re-add
        try {
          await shell('gcloud', [
            'compute', 'instances', 'delete-access-config', VM_NAME,
            '--zone', zone,
            '--access-config-name=vpn-only',
            '--project', project,
          ]);
          await shell('gcloud', [
            'compute', 'instances', 'add-access-config', VM_NAME,
            '--zone', zone,
            '--access-config-name=vpn-only',
            `--address=${staticIp}`,
            '--project', project,
          ]);
        } catch {
          // If it still fails, the IP may already be attached — continue
        }
      }
    },
  );

  // Generate WireGuard server keys on the VM
  let serverPublicKey: string;
  await withSpinner(
    'Generating WireGuard server keys on VM...',
    async () => {
      await vpnSshExecScript(project, zone, [
        'umask 077',
        'wg genkey | sudo tee /etc/wireguard/server_private.key | wg pubkey | sudo tee /etc/wireguard/server_public.key',
      ].join('\n'));
    },
  );

  serverPublicKey = vpnSshExec(project, zone, 'sudo cat /etc/wireguard/server_public.key');

  // Generate client keys on the VM (Windows has no wg/bash locally)
  let clientPrivateKey: string;
  let clientPublicKey: string;

  await withSpinner(
    'Generating WireGuard client keys on VM...',
    async () => {
      await vpnSshExecScript(project, zone, [
        'umask 077',
        'wg genkey | tee /tmp/lox-client-private.key | wg pubkey > /tmp/lox-client-public.key',
      ].join('\n'));
      clientPrivateKey = vpnSshExec(project, zone, 'cat /tmp/lox-client-private.key');
      clientPublicKey = vpnSshExec(project, zone, 'cat /tmp/lox-client-public.key');
      // Clean up keys from VM
      vpnSshExec(project, zone, 'rm -f /tmp/lox-client-private.key /tmp/lox-client-public.key');
    },
  );

  // Configure WireGuard server on VM
  await withSpinner(
    `${strings.configuring} WireGuard server on VM...`,
    async () => {
      const serverPrivateKey = vpnSshExec(project, zone, 'sudo cat /etc/wireguard/server_private.key');

      const serverConf = [
        '[Interface]',
        `PrivateKey = ${serverPrivateKey}`,
        `Address = ${VPN_SERVER_IP}/24`,
        `ListenPort = ${VPN_LISTEN_PORT}`,
        `PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o ${HOST_INTERFACE} -j MASQUERADE`,
        `PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o ${HOST_INTERFACE} -j MASQUERADE`,
        '',
        '[Peer]',
        `PublicKey = ${clientPublicKey!}`,
        `AllowedIPs = ${VPN_CLIENT_IP}/32`,
      ].join('\n');

      await vpnSshExecScript(project, zone, buildServerDeployScript(serverConf));
    },
  );

  // Write client config locally
  // HOME doesn't exist on Windows — fall back to USERPROFILE
  const home = process.env.HOME ?? process.env.USERPROFILE ?? '/tmp';
  const clientConfDir = path.join(home, '.config', 'lox', 'wireguard');
  const clientConfPath = path.join(clientConfDir, 'wg0.conf');

  await withSpinner(
    `${strings.configuring} WireGuard client config...`,
    async () => {
      const clientConf = [
        '[Interface]',
        `PrivateKey = ${clientPrivateKey!}`,
        `Address = ${VPN_CLIENT_IP}/24`,
        '',
        '[Peer]',
        `PublicKey = ${serverPublicKey}`,
        `Endpoint = ${staticIp}:${VPN_LISTEN_PORT}`,
        `AllowedIPs = ${VPN_SUBNET}`,
        'PersistentKeepalive = 25',
      ].join('\n');

      await mkdir(clientConfDir, { recursive: true });
      await writeFile(clientConfPath, clientConf, { mode: 0o600 });
    },
  );

  // Store VPN config in context
  ctx.config.vpn = {
    server_ip: VPN_SERVER_IP,
    subnet: VPN_SUBNET,
    listen_port: VPN_LISTEN_PORT,
    peers: [
      {
        name: 'mac-client',
        ip: VPN_CLIENT_IP,
        public_key: clientPublicKey!,
        added_at: new Date().toISOString(),
      },
    ],
  };

  console.log(chalk.green(`  ✓ WireGuard VPN configured (${staticIp}:${VPN_LISTEN_PORT})`));
  console.log(chalk.dim(`    Client config: ${clientConfPath}`));
  console.log(chalk.dim(`    Activate: sudo wg-quick up ${clientConfPath}`));
  return { success: true };
}
